### ISSUE TITLE
plone.testing 5.0.0. hidden on PyPI

### ISSUE THREAD

**Issue by jensens** [plone/plone.testing#22]
https://pypi.python.org/pypi/plone.testing/5.0.0 is not visible.
see also zestsoftware/zest.releaser#166

**Comment by do3cc** [comment]
I manually toggled visibility.
I am not sure if this can be solved in zest.releaser.
I want the latest patch version for each maintained branch.
How should zest.releaser know what is maintained?
https://pypi.python.org/pypi/plone.testing

**Comment by jensens** [comment]
> How should zest.releaser know what is maintained?

Tell it?
