### ISSUE TITLE
How to run the tests of this package?

### ISSUE THREAD

**Issue by icemac** [plone/plone.testing#25]
There seem to be at least three ways to run the tests for this package (master branch) but non works for me:

1. `python2.7 setup.py test` Installs many packages but does not run any test.
2. `tox`

  - does not work for Python 2.6 (too old).
  - For Python .27 it does not find `.tox/py27/bin/py.test` because it needs to be `pytest` in the path.
  - After changing the path to the pytest executable no tests are run. (Missing `pytest.ini`?)
3. `python2.7 bootstrap.py && bin/buildout && bin/test`

  - has a version conflict: `zope.browserresource 4.1.0 requires 'zope.contenttype>=4.0.1'`
  - After pinning versions of multiple packages (`zope.browserresource`, `zope.browsermenu`, `zope.browserpage`) the tests fail with  `from zope.component.hooks import SiteInfo -> ImportError: No module named hooks` because the pinned zope.component version (3.7.1)  is too old (3.8 is the first one to have `zope.component.hooks`.)
  - Even pinning `zope.component` does not help because of ` IOError: [Errno 2] No such file or directory: '/.../zope.publisher-3.8.0-py2.7.egg/zope/publisher/meta.zcml'`
  - At this point I gave up to try the buildout approach.

Am I missing something?
What is the canonical way to run the tests of this package?
Is there even documentation which I did not find?

**Comment by icemac** [comment]
Are the tests of this package run on a Jenkins server or Travis-CI?

**Comment by gforcada** [comment]
@icemac they seem to run in Plone's jenkins http://jenkins.plone.org/job/plone-5.1-python-2.7/923/console

**Comment by gforcada** [comment]
@icemac with branch https://github.com/plone/plone.testing/tree/gforcada-run-tests they do run with:

```
virtualenv-2.7 .
pip install -U pip zc.buildout setuptools
bin/buildout
bin/test
```

**Comment by icemac** [comment]
@gforcada Thanks for finding this out. I made a PR from your branch.

**Comment by gforcada** [comment]
Thanks I will merge then.
