### ISSUE TITLE
Support zope.testbrowser > 5

### ISSUE THREAD

**Issue by icemac** [plone/plone.testing#36]
The current implementation in `_z2_testbrowser.py` can only support `zope.testbrowser < 5` as it uses `mechanize` which is no longer supported in `zope.testbrowser > 5`.

It is not enough to remove `_z2_testbrowser.py` the tests using it in `z2.rst` should be replaced by code using a Zope WSGI application so `zope.testbrowser > 5` can be used and to make sure there is a clear upgrade path. This requires at least a new layer class to build such a WSGI application.

**Comment by jensens** [comment]
I think this was already solved. Reopen if I am wrong.

**Comment by icemac** [comment]
`_z2_testbrowser.py` is still there and there is nothing in its commit log which indicates that this issue is fixed.

**Comment by gforcada** [comment]
Seems that now it is finally fixed, `mechanize` is nowhere to be found and `zope.rst` is using a WSGI Zope.
