### ISSUE TITLE
WSGIServer layer isolation issues around thread locals (like SiteInfo)

### ISSUE THREAD

**Issue by lukasgraf** [plone/plone.testing#58]
*(Follow-up issue from plone/Products.CMFPlone#2592)*

**Steps to reproduce**

- Set up a coredev buildout using `buildout-py2.cfg`
- `ROBOT_BROWSER=chrome bin/test --all -s plone.app.widgets -s plone.restapi -t test_datetime_widget.robot -t TestBatchingArchetypes`

*(You may want to use `ROBOT_BROWSER=chrome bin/test ...` to run the robot tests with Chrome instead of FF)*

=>

Tests fail with

```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

because a `plone.restapi` got HTML instead of JSON in a response.

---

I've looked into this failure as part of https://github.com/plone/Products.CMFPlone/issues/2592#issuecomment-429538716.

The failure in `plone.restapi` happens because the subscriber registration of the [`mark_as_api_request` for `IPubStart`](https://github.com/plone/plone.rest/blob/b43bf5266876b41256772a0ab2627e6a412588b5/src/plone/rest/configure.zcml#L8-L11) seems to vanish when a robotframework test like the one from `p.a.widgets` runs before it.

This is the difference I'm seeing (all from inside a waitress request handler thread):

---

**Passing test** (just running the `plone.restapi` test alone):

```python
(Pdb) sm = getSiteManager()
(Pdb) print list(sm.registeredHandlers())
[HandlerRegistration(<BaseGlobalComponents test-stack-3>, [IPubStart], u'', mark_as_api_request, File ".../plone/rest/configure.zcml", line 8.2-11.6)]
```

=> Site manager contains the event subscriber registration. Good.

**Failing test** (first the robot test from `p.a.widgets`, then the `plone.restapi` test):

```python
(Pdb) sm = getSiteManager()
(Pdb) print list(sm.registeredHandlers())
[]
```

=> Registration is missing.

---

When I further inspect which exact stacked component registry instance we're working with, I see something strange:

**Passing test:**

```python
(Pdb) sm
<BaseGlobalComponents test-stack-3>
(Pdb) from plone.testing import zca
(Pdb) zca._REGISTRIES
[<BaseGlobalComponents base>, <BaseGlobalComponents test-stack-1>, <BaseGlobalComponents test-stack-2>, <BaseGlobalComponents test-stack-3>]
(Pdb) zca._REGISTRIES[-1] is sm
True
(Pdb) id(zca._REGISTRIES[-1]), id(sm)
(4586995088, 4586995088)
```

=> The current site manager is the last one from `plone.testing.zca`'s component registry stack. Good.

**Failing test:**

```python
(Pdb) sm
<BaseGlobalComponents test-stack-3>
(Pdb) from plone.testing import zca
(Pdb) zca._REGISTRIES
[<BaseGlobalComponents base>, <BaseGlobalComponents test-stack-1>, <BaseGlobalComponents test-stack-2>, <BaseGlobalComponents test-stack-3>]
(Pdb) zca._REGISTRIES[-1] is sm
False
(Pdb) id(zca._REGISTRIES[-1]), id(sm)
(4652502480, 4583929552)
```

=> The current site manager is a different one than the last one from `plone.testing.zca`'s stack, *yet has the same name (`test-stack-3`) / stack depth number*.

---

If we actually poke the last component registry from zca's stack (during the failing test), that's where our subscriber registration would be:

**Failing test:**

```python
(Pdb) print list(zca._REGISTRIES[-1].registeredHandlers())
[HandlerRegistration(<BaseGlobalComponents test-stack-3>, [IPubStart], u'', mark_as_api_request, File ".../plone/rest/configure.zcml", line 8.2-11.6)]
```

This leads be to believe that there's an isolation issue around the component registry with the [`WSGIServer` layer](https://github.com/plone/plone.testing/blob/7e714e8ca93bd58a66e14da98f7717e87f0078b8/src/plone/testing/zope.py#L886-L959).

My hypothesis is this:

The reference to the current site manager is stored on the [`SiteInfo` object in `zope.component.hooks`](https://github.com/zopefoundation/zope.component/blob/52b524b38efe2d449162788fe8445e948246fd21/src/zope/component/hooks.py#L47-L57). `SiteInfo` is **thread local**. Since the `WSGIServer` layer starts its threads on layer setUp, and only tears them down at layer teardown, its threads start off with a `SiteInfo` instance after initial layer setup that is then detached from the main thread's `SiteInfo` (becomes thread-local) for the lifecycle of the layer.

That would then render `plone.testing.zca`'s attempts to provide component registry isolation via its stacked configuration contexts ineffective, because its `pushGlobalRegistry()` / `popGlobalRegistry()` functions operate on the main thread's site manager, not on the waitress thread one's.

In an attempt to confirm this hypothesis, I changed `SiteInfo` to inherit from `object` instead of `threading.local` - and indeed, this did "fix" the test failure. I was also able to reproduce the test failure with other robot tests, not just `p.a.widgets` - the robot tests from `p.a.multilingual` or `p.a.contenttypes` cause exactly the same issue (if they happen to be run *before* the `plone.restapi` test).

/cc @davisagli (*because you indicated you could maybe look into this eventually, and I'm out of my depth with threading issues around webtest/waitress/WSGI to be honest*)

**Comment by pbauer** [comment]
@lukasgraf why are you setting it up with `buildout-py3.cfg`? In Python 3 this should not work at all because `Products.ATContentTypes` is not ported to Python 3. Instead you should use `buildout-py2.cfg` which pulls in all AT packages for the tests. 

Another question: I do not understand why the issue only happens in `TestBatchingArchetypes` and not in `TestBatchingSearch` or any of the other DX testcases that use exactly the same event handler and test the same thing using a very similar testlayer (including `plone.testing.zope.WSGIServer`).

**Comment by jensens** [comment]
I think this is n longer an issue, reopen if I am wrong.
