### ISSUE TITLE
default ZPublisher encoding in Zope 2.13 is set to iso8859-15

### ISSUE THREAD

**Issue by petschki** [plone/plone.testing#62]
referencing this pull request https://github.com/collective/collective.easyform/pull/139 and the discussion here https://github.com/plone/Products.CMFPlone/pull/2810 there are some tests failing due to the default ZPublisher encoding `iso8859-15` in Zope 2.13 ... this needs to be `utf-8` in Plone (see https://github.com/plone/plone.recipe.zope2instance/blob/6.1.4/README.rst#advanced-options)

NOTE: in Zope 4 this is already set to `utf-8` (https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/HTTPResponse.py#L54)

**Comment by petschki** [comment]
@plone/release-team can we have a `4.3.3`of that?

**Comment by gforcada** [comment]
@petschki done!
