### ISSUE TITLE
plone.testing-9.0 hard depends on five/zope2, is that intentional?

### ISSUE THREAD

**Issue by wosc** [plone/plone.testing#86]
Previously I was very happy that plone.testing uses different extras (zca/zodb/etc) for different subsystems, because that way we could easily use it in totally non-zope contexts. But now f281868 introduced a hard dependency on all of zope2, making this usecase impossible. Would you be open to reconsidering this change? Thank you!

**Comment by icemac** [comment]
I think this is a review oversight in the PR. I do not think that `plone.testing` should depend directly on Zope.

CC: @gforcada

**Comment by gforcada** [comment]
🤔 if it can be used without, then sure, maybe the dependency checker was not set up properly the first time I ran it... I will see if it can be changed.

Don't hesitate to ping me frequently as my memory is terrible and I have tons of other things (kids, work, etc) flying over my head 😓

**Comment by gforcada** [comment]
Thanks @davisagli 🙏🏾

**Comment by wosc** [comment]
Thank you very much!
